import { slideFlowAt } from './slideLayout.js';
const moonFloor = (x, z) => {
  const radial = Math.min(1, (x * x + z * z) / (18 * 18));
  return -4 + 5.2 * Math.sqrt(1 - radial);
};
// Per-world terrain and presentation. Keep scene coordinates out of shared controls.
export const worldConfigs = {
  constellationNight:{background:'#49417f',fog:'#49417f',spawn:{x:0,z:17,height:0},bounds:{minX:-18,maxX:18,minZ:-18,maxZ:19},floorAt:()=>0,isSwimming:()=>false,heading:'별과 놀이기구가 떠 있는 보랏빛 밤을 탐험해요.',guide:'회색 길을 따라 달 모양 놀이기구와 로켓 미끄럼틀, 나무와 친구들을 찾아보세요.',alt:'보라색 밤하늘과 별, 노란 초승달 놀이기구, 회색 길, 검은 구름, 주황 로켓 미끄럼틀, 나무와 두 아이.',readyText:'탐험 중 · 달과 로켓, 별빛 친구들을 찾아보세요.',map:[{x:-9,z:-13,label:'초승달'},{x:9,z:-5,label:'로켓'},{x:-13,z:4,label:'나무'},{x:8,z:1,label:'친구들'}]},
  moonCrater:{background:'#17181b',fog:'#292a2d',spawn:{x:0,z:13,height:moonFloor(0,13)},bounds:{minX:-16,maxX:16,minZ:-16,maxZ:16},floorAt:moonFloor,isSwimming:()=>false,heading:'연필로 그린 거대한 달 표면 위를 걸어보세요.',guide:'크기가 서로 다른 둥근 분화구 사이를 걷고 2단 점프로 테두리 위에 올라가 보세요.',alt:'검은 우주 속 회색 달 표면. 크고 작은 원형 분화구와 점 모양 구덩이가 흩어져 있다.',readyText:'탐험 중 · 달 분화구의 크기와 위치를 살펴보세요.',map:[{x:-9,z:-2,label:'큰 분화구'},{x:1,z:2,label:'중앙 분화구'},{x:8,z:1,label:'오른쪽 분화구'}]},
  bananaMilkRecord:{focusHeight:4.2,spawn:{x:0,z:15,height:0},bounds:{minX:-17,maxX:17,minZ:-14,maxZ:17},floorAt:()=>0,isSwimming:()=>false,
    heading:'거대한 바나나우유와 기록 도전 장면을 탐험해요.',guide:'공책과 연필을 지나 흰 계단으로 큰 우유병과 초록 뚜껑에 올라가고, 파란 빨대와 뒤쪽 아이를 올려다보세요.',alt:'검정 단발과 큰 갈색 눈, 파란 상의의 아이가 양손으로 매우 큰 연노랑 바나나우유 병을 잡고 있다. 초록 뚜껑과 파란 빨대, 뒤쪽 바나나 그림·갈색 소파·붉은 창틀, 아래 공책·분홍 연필·회색 신발.',readyText:'탐험 중 · 큰 우유병과 파란 빨대, 공책을 찾아보세요.',map:[{x:-10,z:9,label:'공책'},{x:0,z:-2,label:'바나나우유'},{x:0,z:-8,label:'기록 도전자'},{x:9,z:-13,label:'소파'}]},
  chineseRestaurant:{spawn:{x:0,z:16,height:0},bounds:{minX:-18,maxX:18,minZ:-16,maxZ:18},floorAt:()=>0,isSwimming:()=>false,
    heading:'사람들로 가득한 중식당 식탁 사이를 탐험해요.',guide:'네 식탁과 음식 접시를 둘러보고, 2단 점프로 식탁 위에 올라 붉은 창과 노란 조명을 살펴보세요.',alt:'회색 중식당에 갈색 식탁 네 개와 여러 음식·컵·젓가락, 중앙과 아래쪽에 앉은 손님들, 왼쪽 음식을 든 아이와 오른쪽 노란 상의 직원 두 명, 붉은 격자 창과 천장 조명.',readyText:'탐험 중 · 네 식탁과 많은 손님, 노란 옷 직원을 찾아보세요.',map:[{x:-7,z:-5,label:'왼쪽 식탁'},{x:7,z:-5,label:'오른쪽 식탁'},{x:-7,z:8,label:'앞 식탁 1'},{x:7,z:8,label:'앞 식탁 2'},{x:14,z:-9,label:'직원'}]},
  dessertCafe:{spawn:{x:0,z:15,height:0},bounds:{minX:-18,maxX:18,minZ:-14,maxZ:17},floorAt:()=>0,isSwimming:()=>false,
    heading:'사람보다 큰 두 설빙 사이를 탐험해요.',guide:'중앙의 숟가락 든 인물을 지나 뒤쪽 흰 계단으로 망고 설빙과 커피 토핑 설빙 위에 올라가 보세요.',alt:'회색 매장에 놓인 매우 큰 설빙 두 그릇. 왼쪽 흰 얼음산의 노란 망고 조각과 연유, 오른쪽 갈색 토핑·검은 점·병 두 개와 연유·커피시럽, 중앙 검정 옷의 숟가락 든 사람과 좌우 인물.',readyText:'탐험 중 · 망고 조각과 커피 토핑, 숟가락을 찾아보세요.',map:[{x:-8,z:-4,label:'망고 설빙'},{x:0,z:2,label:'숟가락 인물'},{x:8,z:-4,label:'커피 설빙'}]},
  phoneBedroom:{spawn:{x:0,z:14.5,height:0},bounds:{minX:-15,maxX:15,minZ:-14,maxZ:15},floorAt:()=>0,isSwimming:()=>false,
    heading:'휴대전화를 보는 사람이 누운 방을 탐험해요.',guide:'큰 침대 가장자리로 2단 점프해 누운 사람과 휴대전화를 보고, 책장·책상·파란 창문도 둘러보세요.',alt:'회색 방 중앙의 큰 침대와 똑바로 누워 흰 휴대전화를 보는 한 사람, 오른쪽 위 파란 창과 구름·건물, 왼쪽 책장과 책, 왼쪽 아래 책상과 모니터.',readyText:'탐험 중 · 침대 위 휴대전화와 창밖 풍경을 찾아보세요.',map:[{x:2,z:-1,label:'큰 침대'},{x:-10,z:-8,label:'책장'},{x:-11,z:7,label:'책상'},{x:10,z:-14,label:'창문'}]},
  roadHome:{spawn:{x:0,z:17,height:0},bounds:{minX:-20,maxX:20,minZ:-15,maxZ:19},floorAt:()=>0,isSwimming:()=>false,
    heading:'물가 앞 넓은 교차로와 돌아가는 차를 탐험해요.',guide:'노랑·검정 차단기를 지나 중앙 자동차의 보닛과 지붕에 올라가고, 난간 너머 작은 붉은 배를 찾아보세요.',alt:'넓은 회색 교차로, 중앙의 검정 자동차, 아래 노랑·검정 차단기, 양쪽 초록 잔디, 뒤쪽 검정 난간과 나무들, 파란 물 위 작은 붉은 배.',readyText:'탐험 중 · 중앙 자동차와 난간 너머 붉은 배를 찾아보세요.',map:[{x:0,z:12,label:'차단기'},{x:0,z:-4,label:'자동차'},{x:0,z:-13,label:'난간'},{x:12,z:-13,label:'붉은 배 보기'}]},
  movingCity:{spawn:{x:0,z:15,height:0},bounds:{minX:-19,maxX:19,minZ:-18,maxZ:18},floorAt:()=>0,isSwimming:()=>false,
    heading:'거대한 택시가 있는 움직이는 도시를 탐험해요.',guide:'오토바이와 작은 차를 지나 중앙 택시의 보닛·트렁크·지붕에 2단 점프로 올라가고, 뒤쪽 빌딩 숲을 올려다보세요.',alt:'회색 고층건물과 파란 창이 가득한 도시. 전경의 매우 큰 짙은 회색 택시, 연두색 Taxi 표지와 큰 바퀴·파란 창·붉은 후미등, 왼쪽 오토바이 운전자와 오른쪽 작은 차.',readyText:'탐험 중 · 큰 택시와 양옆의 교통수단을 찾아보세요.',map:[{x:-14,z:5,label:'오토바이'},{x:0,z:-3,label:'큰 택시'},{x:14,z:4,label:'작은 차'},{x:3,z:-16,label:'빌딩 숲'}]},
  weekendRoom:{spawn:{x:0,z:14,height:0},bounds:{minX:-15,maxX:15,minZ:-14,maxZ:15},floorAt:()=>0,isSwimming:()=>false,
    heading:'주말 놀이방의 책상과 보드게임을 탐험해요.',guide:'바닥의 주사위와 게임판을 둘러보고 파란 의자와 책상 위로 2단 점프해 노트와 사진 게시판을 가까이 보세요.',alt:'초록색 방 중앙의 큰 회색 책상과 노트, 파란 의자, 벽의 사진 게시판과 창문, 오른쪽 침대, 바닥의 보드게임·주사위·색연필과 고양이 모양 쿠션, 왼쪽 사람.',readyText:'탐험 중 · 책상 위 노트와 바닥 놀이 도구를 찾아보세요.',map:[{x:-10,z:8,label:'보드게임'},{x:1,z:-5,label:'책상'},{x:11,z:7,label:'침대'},{x:12,z:0,label:'고양이 쿠션'}]},
  soccerField:{spawn:{x:0,z:12,height:0},bounds:{minX:-18,maxX:18,minZ:-14,maxZ:14},floorAt:()=>0,isSwimming:()=>false,
    heading:'슛이 날아가는 축구장 한가운데를 달려요.',guide:'센터서클을 지나 두 선수와 공의 궤적을 보고, 양쪽 골대 기둥과 크로스바에도 2단 점프로 올라가 보세요.',alt:'위에서 본 연한 초록 축구장, 좌우 골대, 검은 중앙선과 센터서클, 노란 상의 선수와 파란 골키퍼, 분홍·검정 공과 날아간 흔적.',readyText:'탐험 중 · 슈터와 골키퍼, 날아가는 공을 찾아보세요.',map:[{x:-16,z:0,label:'왼쪽 골대'},{x:-5,z:-5,label:'슈터'},{x:7,z:7,label:'골키퍼'},{x:16,z:0,label:'오른쪽 골대'}]},
  dabotap:{spawn:{x:0,z:10,height:0},bounds:{minX:-20,maxX:20,minZ:-23,maxZ:19},floorAt:()=>0,isSwimming:()=>false,
    heading:'정면 계단을 올라 다보탑을 가까이 살펴봐요.',guide:'긴 돌계단을 따라 기단에 오르고, 2단 점프로 넓은 처마와 여러 층의 기둥 구조를 탐험해 보세요.',
    alt:'푸른 하늘과 노란 해 아래 중앙의 매우 큰 회색 다보탑. 정면 긴 계단과 여러 층 기단·기둥·처마, 양쪽 나무와 왼쪽의 작은 관람 인물.',readyText:'탐험 중 · 정면 계단과 꼭대기 장식을 올려다보세요.',map:[{x:0,z:5,label:'정면 계단'},{x:0,z:-7,label:'다보탑'},{x:-12,z:7,label:'관람객'}]},
  dolmenField:{
    spawn:{x:0,z:14,height:0},bounds:{minX:-19,maxX:19,minZ:-22,maxZ:18},floorAt:()=>0,isSwimming:()=>false,
    heading:'초록 들판의 고인돌 사이를 탐험해요.',guide:'앞쪽 작은 돌을 발판 삼아 오르고, 좌우 고인돌의 기둥 사이와 덮개돌 위를 살펴보세요.',
    alt:'푸른 하늘 아래 넓은 초록 들판, 좌우 탁자형 고인돌 두 개, 중앙 큰 바위와 앞쪽 작은 돌 세 개, 왼쪽 나무와 아래 황토색 길.',
    readyText:'탐험 중 · 두 고인돌과 중앙 큰 바위를 찾아보세요.',map:[{x:-8,z:-6,label:'왼쪽 고인돌'},{x:1,z:-8,label:'큰 바위'},{x:9,z:-8,label:'오른쪽 고인돌'}],
  },
  sunsetValley: {
    spawn:{x:0,z:13,height:0},bounds:{minX:-18,maxX:18,minZ:-27,maxZ:17},floorAt:()=>0,isSwimming:()=>false,
    heading:'두 산 사이 붉은 노을을 향해 걸어요.',
    guide:'분홍빛 계곡길을 따라 해 쪽으로 가거나, 양쪽의 낮은 능선 계단을 2단 점프로 올라가 보세요.',
    alt:'진한 초록 산과 연한 초록 산 사이 낮게 뜬 붉은 해, 주황·분홍 계곡, 붉은 저녁놀과 파란 하늘, 회색 구름 두 개.',
    readyText:'탐험 중 · 산 사이 붉은 해와 두 구름을 찾아보세요.',map:[{x:-11,z:-13,label:'초록 산'},{x:0,z:-25,label:'노을'},{x:11,z:-13,label:'연두 산'}],
  },
  aquarium: {
    spawn:{x:0,z:-9,height:0,yaw:Math.PI},bounds:{minX:-16,maxX:16,minZ:-14,maxZ:18},
    floorAt:(x,z)=>z<-4?0:-.85*Math.min(1,(z+4)/2),isSwimming:p=>p.z>-3.7&&p.height<-.35,
    heading:'먹이존에서 배를 타고 물속 친구들을 만나요!',
    guide:'부두에서 계단을 따라 큰 배에 올라가 보세요. 물로 뛰어들면 물고기와 해파리 사이를 헤엄칠 수 있어요.',
    alt:'연한 파란 물 위 전경의 흰색·주황색 큰 배와 네 사람, 뒤쪽 먹이존 판매대와 두 번째 배, 물속 여러 물고기와 보라색·흰색 해파리.',
    waterLabel:'수족관 물',readyText:'탐험 중 · 큰 배와 먹이존, 물속 생물을 찾아보세요.',
    map:[{x:-9,z:-12,label:'먹이존'},{x:-3,z:4,label:'큰 배'},{x:8,z:-7,label:'작은 배'}],waterRect:{x:-16,z:-4,width:32,depth:22},
  },
  waterparkPool: {
    spawn:{x:0,z:16,height:-.85},bounds:{minX:-17,maxX:17,minZ:-18,maxZ:18},
    floorAt:(x,z)=>z<-2?0:-.85*Math.min(1,(z+2)/2),isSwimming:p=>p.z>-1.7&&p.height<-.35,
    heading:'노란 미끄럼틀과 물놀이 성',guide:'튜브 사이를 헤엄치고 양쪽 계단으로 미끄럼틀과 중앙 놀이 성에 올라가 보세요.',
    alt:'왼쪽을 크게 감싸는 노란 미끄럼틀, 중앙 붉은 놀이 성과 초록 터널, 오른쪽 노랑·초록 미끄럼틀. 수영모를 쓴 여러 사람과 튜브.',
    waterLabel:'수영장',readyText:'탐험 중 · 성과 양쪽 미끄럼틀을 찾아보세요',map:[{x:-9,z:-8,label:'노랑'},{x:-2,z:-8,label:'놀이성'},{x:10,z:-6,label:'초록'}],waterRect:{x:-17,z:-2,width:34,depth:20},
  },
  happyWaterpark: {
    spawn: {x:0,z:15,height:-0.85},
    bounds:{minX:-16,maxX:16,minZ:-16,maxZ:18},
    floorAt:(x,z)=>z<=-3?0:-0.85*Math.min(1,(z+3)/2),
    isSwimming:p=>p.z>-2.7&&p.height< -0.35,
    flowAt:slideFlowAt,
    heading:'두 미끄럼틀을 타고 풍덩!',
    guide:'뒤쪽 마른 바닥에서 양옆 회색 계단을 올라가세요. 미끄럼틀 가운데로 들어가면 물 쪽으로 미끄러져요.',
    alt:'왼쪽 큰 노란 해, 가운데 파란 굽은 미끄럼틀과 오른쪽 긴 빨간 미끄럼틀. 위쪽 노란 출발 공간과 양옆 회색 계단. 미끄럼틀 쪽 세 사람과 물속 세 사람, 초록·노랑 튜브.',
    waterLabel:'물놀이',readyText:'탐험 중 · 회색 계단으로 미끄럼틀 위까지',
    map:[{x:-3,z:-9,label:'파랑'},{x:9,z:-10,label:'빨강'},{x:-7,z:4,label:'계단'},{x:13,z:5,label:'계단2'}],
    waterRect:{x:-16,z:-3,width:32,depth:21},
  },
  waterparkDay: {
    spawn: { x: 0, z: 14, height: -0.85 },
    bounds: { minX: -16, maxX: 16, minZ: -17, maxZ: 17 },
    floorAt: (x, z) => z <= -1 ? 0 : -0.85 * Math.min(1, (z + 1) / 2),
    isSwimming: p => p.z > -0.7 && p.height < -0.35,
    heading: '물총 놀이와 수박 피크닉',
    guide: '튜브와 초록 매트에 올라가고, 울타리 가운데 열린 통로로 잔디와 피크닉 자리를 오가 보세요.',
    alt: '앞쪽 물속 세 사람, 수박 모양 튜브와 초록 매트, 물총과 공과 빨강·하양 튜브. 뒤쪽 주황 기둥과 빨간 줄, 안전주의 표지. 잔디 위 고양이와 새, 오른쪽 수박·그릇이 놓인 돗자리와 파란 모자의 사람.',
    waterLabel: '물놀이', readyText: '탐험 중 · 가운데 통로로 물과 잔디를 오가요',
    map: [{ x: -8, z: 7, label: '튜브' }, { x: 7, z: -8, label: '피크닉' }, { x: 0, z: -1, label: '통로' }],
    waterRect: { x: -16, z: -1, width: 32, depth: 18 },
  },
  divingPool: {
    spawn: { x: 0, z: 14, height: 0 },
    bounds: { minX: -14.5, maxX: 16.5, minZ: -19, maxZ: 15.5 },
    floorAt: (x, z) => x > -7 && x < 15 && z > -16 && z < 12 ? -0.85 * Math.min(1, (12 - z) / 2) : 0,
    isSwimming: p => p.x > -7 && p.x < 15 && p.z > -16 && p.z < 12 && p.height < -0.35,
    heading: '출발대에서 파란 물속으로!',
    guide: '왼쪽 출발대의 작은 계단을 올라 점프해 보세요. 수영장 앞쪽 얕은 경사로로 다시 나올 수 있어요.',
    alt: '왼쪽 회색 바닥 위 초록·파랑 출발대 다섯 개(위아래 일부 잘림), 오른쪽 파란 수영장과 빨강·파랑 레인 줄 네 줄, 가운데 점무늬 수영복을 입고 팔을 뻗어 다이빙하는 한 사람.',
    waterLabel: '수영장', readyText: '탐험 중 · 출발대에서 점프해 보세요',
    map: [{ x: -9, z: 0, label: '출발대' }, { x: 3, z: 0, label: '레인' }, { x: 4, z: 11, label: '출구' }],
    waterRect: { x: -7, z: -16, width: 22, depth: 28 },
    seaPercent: 100,
  },
  beach: {
    spawn: { x: 0, z: 11, height: 0 },
    bounds: { minX: -14, maxX: 14, minZ: -34, maxZ: 15 },
    floorAt: (x, z) => z >= -8.5 ? 0 : -0.85 * Math.min(1, (-z - 8.5) / 2),
    isSwimming: p => p.z < -8.8 && p.height < -0.35,
    heading: '색연필 바다에 발을 들여놓아요.',
    guide: '튜브 위로 뛰어오르고, 바다에 들어가 돌고래 곁에서 헤엄쳐 보세요.',
    alt: '학생이 그린 해변. 왼쪽 구명조끼 가게, 가운데 빨강·노랑 튜브, 오른쪽 삼색 파라솔과 돗자리, 뒤쪽 바다와 돌고래.',
    map: [{ x: -8, z: 5, label: '가게' }, { x: -1.8, z: 2.2, label: '◎' }, { x: 7, z: 0, label: '✳' }],
    seaPercent: 51,
  },
  seaDay: {
    spawn: { x: 0, z: 7, height: -0.85 },
    bounds: { minX: -16, maxX: 17, minZ: -22, maxZ: 14 },
    floorAt: () => -0.85,
    isSwimming: p => p.height < -0.35,
    heading: '파란 물결 속, 함께 헤엄쳐요.',
    guide: '세 친구 곁을 헤엄치고, 오른쪽 발판의 앞쪽 낮은 계단으로 올라가 보세요.',
    alt: '파란 색연필로 가득 칠한 바다. 왼쪽 분홍색과 파란색 옷의 두 사람, 그 앞에 가로로 헤엄치는 검은색 옷의 사람, 오른쪽 밝은 칸과 파란 격자의 긴 구조물.',
    map: [{ x: -7, z: -4, label: '친구들' }, { x: 7, z: -5, label: '발판' }, { x: 7, z: 1, label: '계단' }],
    seaPercent: 100,
  },
};
