import React,{useEffect,useMemo} from 'react';import {Edges} from '@react-three/drei';import {DoubleSide,MeshStandardMaterial} from 'three';import Character from '../Character';import {pencilTexture} from '../materials';
function Solid({position,scale=[1,1,1],rotation,material,shape='box',args,walkable=true}){return <mesh position={position} scale={scale} rotation={rotation} material={material} castShadow receiveShadow userData={walkable?{walkable:true}:{nonSolid:true}}>{shape==='box'?<boxGeometry/>:shape==='sphere'?<sphereGeometry args={[1,18,14]}/>:shape==='torus'?<torusGeometry args={args||[1,.3,10,22]}/>:<cylinderGeometry args={args||[1,1,1,18]}/>} {shape==='box'&&<Edges color="#514f4d"/>}</mesh>}
export default function BananaMilkRecord(){const m=useMemo(()=>Object.fromEntries(Object.entries({floor:'#d6c6ae',wall:'#d9d7c8',sofa:'#73655c',yellow:'#e2dd78',green:'#66a65b',blue:'#4c83bb',skin:'#d8a07d',black:'#29282a',white:'#eee9dd',pink:'#d7567b',brown:'#8d6045'}).map(([k,c],i)=>{const map=pencilTexture(c,760+i);map.repeat.set(['floor','wall','sofa'].includes(k)?7:2,['floor','wall','sofa'].includes(k)?7:2);return[k,new MeshStandardMaterial({map,roughness:1,side:DoubleSide})]})),[]);useEffect(()=>()=>Object.values(m).forEach(x=>{x.map.dispose();x.dispose()}),[m]);return <group>
 <Solid position={[0,-.32,0]} scale={[36,.55,34]} material={m.floor}/><Solid position={[0,7,-16]} scale={[36,14,.5]} material={m.wall}/><Solid position={[9,4,-14]} scale={[15,7,3]} material={m.sofa}/><Solid position={[9,8,-14]} scale={[15,2.2,2.5]} material={m.sofa}/>
 {/* giant background child keeps the portrait scale of the source */}
 <group position={[0,2.2,-7]} scale={4.2}><Character shirt="#5c8dbb" pants="#d7d06a" variant={2} behavior="rest"/></group>
 {/* oversized bottle and straw are the primary climbable object */}
 <Solid position={[0,3.1,-2]} scale={[5.3,6.2,4.6]} shape="cylinder" args={[.82,1,1,22]} material={m.yellow}/><Solid position={[0,6.45,-2]} scale={[3.6,.55,3.3]} shape="cylinder" material={m.green}/><Solid position={[0,9,-2]} scale={[.35,5,.35]} shape="cylinder" material={m.blue}/>
 <Solid position={[-6,5,-1]} scale={[2.2,.65,1.4]} shape="sphere" material={m.skin} walkable={false}/><Solid position={[6,5,-1]} scale={[2.2,.65,1.4]} shape="sphere" material={m.skin} walkable={false}/>
 <group position={[-10,.1,9]}><Solid scale={[6,.25,5]} material={m.white}/><Solid position={[0,.2,0]} scale={[.08,.12,4.5]} material={m.pink} walkable={false}/></group><Solid position={[-2,.5,10]} scale={[.25,1.4,.25]} rotation={[0,0,-.2]} shape="cylinder" material={m.pink}/><Solid position={[10,.6,9]} scale={[4,1.1,2]} material={m.sofa}/>
 {/* giant banana drawing on the rear wall */}<Solid position={[-9,8,-15]} scale={[4,.6,2]} rotation={[0,0,-.5]} shape="torus" args={[1,.35,10,24,Math.PI*1.35]} material={m.yellow} walkable={false}/>
 {Array.from({length:14},(_,i)=><Solid key={i} position={[-5.5,(i+1)*.32-.16,5-i*.48]} scale={[1.6,.32,.58]} material={m.white}/>) }
 </group>}
