import React,{useEffect,useMemo} from 'react';import {Edges} from '@react-three/drei';import {DoubleSide,MeshStandardMaterial} from 'three';import Character from '../Character';import {pencilTexture} from '../materials';
function Solid({position,scale=[1,1,1],rotation,material,shape='box',walkable=true}){return <mesh position={position} scale={scale} rotation={rotation} material={material} castShadow receiveShadow userData={walkable?{walkable:true}:{nonSolid:true}}>{shape==='box'?<boxGeometry/>:shape==='sphere'?<sphereGeometry args={[1,14,10]}/>:<cylinderGeometry args={[1,1,1,16]}/>} {shape==='box'&&<Edges color="#514c4a"/>}</mesh>}
function Person({position,shirt,variant=0,behavior='sit',scale=1.25,rotation=0}){return <group position={position} scale={scale} rotation={[0,rotation,0]}><Character shirt={shirt} pants="#47769a" variant={variant} behavior={behavior}/></group>}
function Table({position,m,food=true}){return <group position={position}><Solid position={[0,1.25,0]} scale={[6,.35,3.2]} material={m.wood}/>{[-2.5,2.5].flatMap(x=>[-1.2,1.2].map(z=><Solid key={`${x}${z}`} position={[x,.6,z]} scale={[.3,1.2,.3]} material={m.dark}/>))}{food&&<><Solid position={[-1,1.58,0]} scale={[.8,.12,.8]} shape="cylinder" material={m.white}/><Solid position={[1,1.58,0]} scale={[.8,.12,.8]} shape="cylinder" material={m.red}/><Solid position={[2,1.7,.6]} scale={[.18,.7,.18]} shape="cylinder" material={m.orange}/></>}</group>}
export default function ChineseRestaurant(){const m=useMemo(()=>Object.fromEntries(Object.entries({floor:'#777777',wall:'#999895',wood:'#9d644a',dark:'#343436',white:'#e6e1d7',red:'#a65754',yellow:'#e0d446',orange:'#d78342',blue:'#5283a7',green:'#729d66'}).map(([k,c],i)=>{const map=pencilTexture(c,710+i);map.repeat.set(['floor','wall'].includes(k)?8:2,['floor','wall'].includes(k)?8:2);return[k,new MeshStandardMaterial({map,roughness:1,side:DoubleSide})]})),[]);useEffect(()=>()=>Object.values(m).forEach(x=>{x.map.dispose();x.dispose()}),[m]);return <group>
 <Solid position={[0,-.32,0]} scale={[40,.55,38]} material={m.floor}/><Solid position={[0,7,-18]} scale={[40,14,.5]} material={m.wall}/><Solid position={[0,7,-17.7]} scale={[16,8,.2]} material={m.red} walkable={false}/>{[-13,-8,-3,3,8,13].map(x=><Solid key={x} position={[x,13,-16]} scale={[.5,.5,.5]} shape="sphere" material={m.yellow} walkable={false}/>) }
 <Table position={[-7,0,-5]} m={m}/><Table position={[7,0,-5]} m={m}/><Table position={[-7,0,8]} m={m}/><Table position={[7,0,8]} m={m}/>
 <Person position={[-7,1.5,-7]} shirt="#efe6dc" variant={1} behavior="sit"/><Person position={[5,1.5,-7]} shirt="#7ab276" variant={2}/><Person position={[8,1.5,-7]} shirt="#4d83aa" variant={3}/>
 <Person position={[-8,1.5,6]} shirt="#d96e6a" variant={0}/><Person position={[-5,1.5,6]} shirt="#e4c262" variant={2}/><Person position={[6,1.5,6]} shirt="#efdfd2" variant={1}/><Person position={[9,1.5,6]} shirt="#7197b4" variant={3}/>
 <Person position={[-15,0,-1]} shirt="#e4e1d8" variant={2} behavior="wave"/><Solid position={[-13.7,1.2,-1]} scale={[.7,.12,.7]} shape="cylinder" material={m.red} walkable={false}/>
 <Person position={[-14,0,9]} shirt="#d889a0" variant={3} behavior="wave" scale={1}/>
 <Person position={[13,0,-9]} shirt="#d6d74a" variant={0} behavior="chat"/><Person position={[16,0,-9]} shirt="#d6d74a" variant={1} behavior="chat"/>
 </group>}
