import React,{useEffect,useMemo} from 'react';import {Edges} from '@react-three/drei';import {DoubleSide,MeshStandardMaterial} from 'three';import Character from '../Character';import {pencilTexture} from '../materials';
function Solid({position,scale=[1,1,1],rotation,material,shape='box',args,walkable=true}){return <mesh position={position} scale={scale} rotation={rotation} material={material} castShadow receiveShadow userData={walkable?{walkable:true}:{nonSolid:true}}>{shape==='box'?<boxGeometry/>:shape==='sphere'?<sphereGeometry args={[1,16,12]}/>:shape==='cone'?<coneGeometry args={args||[1,1,18]}/>:<cylinderGeometry args={args||[1,1,1,18]}/>} {shape==='box'&&<Edges color="#555052"/>}</mesh>}
function Bowl({x,m,type}){const mango=type==='mango';return <group position={[x,0,-4]}><Solid position={[0,1,0]} scale={[5.7,2.2,5.7]} shape="cylinder" args={[1.15,.85,1,22]} material={m.white}/><Solid position={[0,4.1,0]} scale={[4.8,5.5,4.8]} shape="cone" args={[1,1,24]} material={m.ice}/><Solid position={[0,7,0]} scale={[1.35,1.35,1.35]} shape="sphere" material={m.ice}/>{Array.from({length:mango?9:14},(_,i)=>{const a=i*2.4,r=1.1+(i%3)*.75,y=3.8+(i%4)*.75;return <Solid key={i} position={[Math.cos(a)*r,y,Math.sin(a)*r]} scale={mango?[.55,.35,.65]:[.24,.24,.24]} shape={mango?'box':'sphere'} material={mango?m.yellow:m.dark} walkable={false}/>})}{!mango&&<><Solid position={[-1.2,7.2,0]} scale={[.55,2,.55]} shape="cylinder" material={m.black} walkable={false}/><Solid position={[.3,7.3,0]} scale={[.55,2,.55]} shape="cylinder" material={m.brown} walkable={false}/></>}</group>}
function Person({position,shirt,variant,scale=1.5,behavior='wave'}){return <group position={position} scale={scale}><Character shirt={shirt} pants="#44464a" variant={variant} behavior={behavior}/></group>}
export default function DessertCafe(){const m=useMemo(()=>Object.fromEntries(Object.entries({floor:'#55575a',wall:'#c4c4c1',white:'#efeee8',ice:'#dddcd4',yellow:'#e1c51e',brown:'#8b472d',dark:'#392f2d',black:'#202225',blue:'#326db0',skin:'#d69a76'}).map(([k,c],i)=>{const map=pencilTexture(c,660+i);map.repeat.set(['floor','wall'].includes(k)?8:2,['floor','wall'].includes(k)?8:2);return[k,new MeshStandardMaterial({map,roughness:1,side:DoubleSide})]})),[]);useEffect(()=>()=>Object.values(m).forEach(x=>{x.map.dispose();x.dispose()}),[m]);return <group>
 <Solid position={[0,-.32,0]} scale={[40,.55,34]} material={m.floor}/><Solid position={[0,7,-16]} scale={[40,14,.5]} material={m.wall}/><Solid position={[0,13,-15.5]} scale={[40,1.2,.3]} material={m.yellow} walkable={false}/>
 <Bowl x={-8} m={m} type="mango"/><Bowl x={8} m={m} type="coffee"/>
 <Person position={[0,0,2]} shirt="#222326" variant={2} behavior="wave"/><Solid position={[-1.4,1.4,2]} scale={[.15,2,.15]} rotation={[0,0,-.8]} shape="cylinder" material={m.white} walkable={false}/>
 <Person position={[-15,0,3]} shirt="#336cb0" variant={1}/><Person position={[15,0,4]} shirt="#3f87bf" variant={3} scale={.9}/>
 {/* shallow steps are added behind each bowl so their large food surfaces are reachable */}
 {[-8,8].map(x=><group key={x}><Solid position={[x+(x<0?2.2:-2.2),3.45,1.5]} scale={[1.2,.16,13.1]} rotation={[.565,0,0]} material={m.white}/>{Array.from({length:18},(_,i)=><Solid key={i} position={[x,(i+1)*.38-.19,7-i*.62]} scale={[1.8,.38,.7]} material={m.white}/>)}</group>)}
 </group>}
