import React,{useEffect,useMemo} from 'react';import {Edges} from '@react-three/drei';import {DoubleSide,MeshStandardMaterial} from 'three';import {pencilTexture} from '../materials';
function Solid({position,scale=[1,1,1],rotation,material,shape='box',walkable=true}){return <mesh position={position} scale={scale} rotation={rotation} material={material} castShadow receiveShadow userData={walkable?{walkable:true}:{nonSolid:true}}>{shape==='box'?<boxGeometry/>:<sphereGeometry args={[1,16,12]}/>} {shape==='box'&&<Edges color="#505052"/>}</mesh>}
function LyingPerson({m}){return <group position={[0,2.65,-.5]} userData={{nonSolid:true}}><Solid position={[0,.6,-3]} scale={[1.25,.55,1.3]} shape="sphere" material={m.skin} walkable={false}/><Solid position={[0,.8,-3.8]} scale={[1.2,.35,.6]} shape="sphere" material={m.dark} walkable={false}/><Solid position={[0,.55,-.7]} scale={[2.2,.55,3.2]} material={m.bed} walkable={false}/><Solid position={[0,.58,1.25]} scale={[2.2,.58,1.1]} material={m.dark} walkable={false}/>{[-.72,.72].map(x=><React.Fragment key={x}><Solid position={[x,.52,2.65]} scale={[.58,.45,2]} material={m.skin} walkable={false}/><Solid position={[x,.5,4]} scale={[.68,.38,.8]} shape="sphere" material={m.skin} walkable={false}/><Solid position={[x*1.9,.9,-.8]} scale={[.5,.4,2.6]} rotation={[0,x*.18,0]} material={m.skin} walkable={false}/></React.Fragment>)}</group>}
export default function PhoneBedroom(){const m=useMemo(()=>Object.fromEntries(Object.entries({room:'#b4b3b0',bed:'#aaa9a5',sheet:'#bebdb9',blue:'#4f94c9',skin:'#d69a76',dark:'#343436',white:'#eeeae0',wood:'#9b583d',green:'#74a949',orange:'#d47737'}).map(([k,c],i)=>{const map=pencilTexture(c,610+i);map.repeat.set(['room','bed'].includes(k)?7:2,['room','bed'].includes(k)?7:2);return[k,new MeshStandardMaterial({map,roughness:1,side:DoubleSide})]})),[]);useEffect(()=>()=>Object.values(m).forEach(x=>{x.map.dispose();x.dispose()}),[m]);return <group>
 <Solid position={[0,-.32,0]} scale={[34,.55,34]} material={m.room}/><Solid position={[0,6,-16]} scale={[34,12,.5]} material={m.room}/>
 <group position={[2,0,-1]}><Solid position={[0,1,0]} scale={[12,2,17]} material={m.bed}/><Solid position={[0,2.1,0]} scale={[11.2,.35,16]} material={m.sheet}/><Solid position={[0,2.55,-6]} scale={[9,.7,3]} material={m.white}/>
  <LyingPerson m={m}/><Solid position={[0,3.95,-.7]} scale={[1.2,.12,1.8]} material={m.white} walkable={false}/><Solid position={[0,4.03,-.7]} scale={[.75,.04,1.2]} material={m.dark} walkable={false}/>
 </group>
 <group position={[10,7,-15.2]}><Solid scale={[8,5,.25]} material={m.blue}/>{[-2.7,0,2.7].map(x=><Solid key={x} position={[x,0,.2]} scale={[.18,5,.2]} material={m.dark}/>) }<Solid position={[0,0,.2]} scale={[8,.18,.2]} material={m.dark}/>{[-2,1.2].map((x,i)=><Solid key={x} position={[x,1.3,.4]} scale={[1.7,.55,.1]} shape="sphere" material={m.white} walkable={false}/>)}</group>
 <group position={[-10,0,-8]}><Solid position={[0,2,0]} scale={[6,4,1.8]} material={m.wood}/>{[-1.8,0,1.8].map((x,i)=><Solid key={x} position={[x,2.1,1]} scale={[1.2,2.9,.25]} material={[m.green,m.orange,m.white][i]}/>)}</group>
 <group position={[-11,0,7]}><Solid position={[0,1.8,0]} scale={[7,.4,5]} material={m.room}/>{[-3,3].flatMap(x=>[-2,2].map(z=><Solid key={`${x}${z}`} position={[x,.9,z]} scale={[.35,1.8,.35]} material={m.dark}/>))}<Solid position={[0,3,-1]} scale={[4,2.4,.35]} material={m.dark}/><Solid position={[0,3,-.78]} scale={[3.3,1.7,.04]} material={m.blue} walkable={false}/></group>
 </group>}
