import React,{useEffect,useMemo} from 'react';import {Edges} from '@react-three/drei';import {DoubleSide,MeshStandardMaterial} from 'three';import {pencilTexture} from '../materials';
function Solid({position,scale=[1,1,1],rotation,material,shape='box',walkable=true}){return <mesh position={position} scale={scale} rotation={rotation} material={material} castShadow receiveShadow userData={walkable?{walkable:true}:{nonSolid:true}}>{shape==='box'?<boxGeometry/>:shape==='sphere'?<sphereGeometry args={[1,16,12]}/>:shape==='cone'?<coneGeometry args={[1,1,8]}/>:<cylinderGeometry args={[1,1,1,16]}/>} {shape==='box'&&<Edges color="#414345"/>}</mesh>}
function Wheel({position,m}){return <Solid position={position} scale={[.8,.34,.8]} rotation={[Math.PI/2,0,0]} shape="cylinder" material={m.black}/>}
export default function RoadHome(){const m=useMemo(()=>Object.fromEntries(Object.entries({road:'#77787a',grass:'#5a9b58',edge:'#b75c48',water:'#3f8bc6',rail:'#303335',tree:'#69ad32',tree2:'#3e934f',car:'#25282b',glass:'#759bc0',yellow:'#e6c11d',red:'#bf2434',white:'#deded6',black:'#1f2224'}).map(([k,c],i)=>{const map=pencilTexture(c,560+i);map.repeat.set(['road','grass','water'].includes(k)?8:2,['road','grass','water'].includes(k)?8:2);return[k,new MeshStandardMaterial({map,roughness:1,side:DoubleSide})]})),[]);useEffect(()=>()=>Object.values(m).forEach(x=>{x.map.dispose();x.dispose()}),[m]);return <group>
 <Solid position={[0,-.32,2]} scale={[42,.55,40]} material={m.road}/><Solid position={[0,.01,-24]} scale={[50,.08,16]} material={m.water} walkable={false}/>
 <Solid position={[-15,.02,10]} scale={[10,.12,16]} material={m.grass}/><Solid position={[15,.02,10]} scale={[10,.12,16]} material={m.grass}/>
 {/* rear rail and alternating trees preserve the strong horizontal band */}
 <Solid position={[0,1.2,-15]} scale={[40,.18,.18]} material={m.rail}/>{[-18,-14,-10,-6,6,10,14,18].map((x,i)=><group key={x} position={[x,0,-14]}><Solid position={[0,.85,0]} scale={[.22,1.7,.22]} material={m.rail}/><Solid position={[0,2.1,0]} scale={[1.2,2.5,1]} shape="cone" material={i%2?m.tree2:m.tree}/></group>)}
 <group position={[0,0,-4]}><Solid position={[0,1.2,0]} scale={[5,2.2,3.5]} material={m.car}/><Solid position={[0,2.35,-.25]} scale={[3.4,1.25,3]} material={m.car}/><Solid position={[0,2.45,1.28]} scale={[2.5,.75,.08]} material={m.glass}/><Solid position={[0,.75,1.78]} scale={[2.4,.65,.08]} material={m.white}/><Wheel position={[-1.7,.45,1.8]} m={m}/><Wheel position={[1.7,.45,1.8]} m={m}/></group>
 <group position={[0,0,12]}><Solid position={[-7,.8,0]} scale={[1.2,1.6,3]} material={m.yellow}/><Solid position={[7,.8,0]} scale={[1.2,1.6,3]} material={m.yellow}/>{Array.from({length:12},(_,i)=><Solid key={i} position={[-5.5+i,1.5,0]} scale={[1,.32,.35]} material={i%2?m.yellow:m.black}/>)}</group>
 <group position={[12,.15,-26]}><Solid scale={[2.2,.3,1]} material={m.red}/><Solid position={[0,.9,0]} scale={[.12,1.8,.12]} material={m.black}/><Solid position={[.7,1.1,0]} scale={[1.3,.7,.08]} material={m.red} walkable={false}/></group>
 </group>}
